sudo: required

# Travis doesn't provide a wide variety of host environments to run on, so we
# rely on Docker to provide these instead.
services:
  - docker

# It is not really needed, other than for showing correct language tag in
# Travis CI build log.
language: cpp

# The matrix of targets that we're interested in.
env:
  - HOST="ubuntu:16.04" CXXFLAGS="-Og -fsanitize=address"
  - HOST="ubuntu:16.04" CXXFLAGS="-O2"
  - HOST="ubuntu:16.04" CXXFLAGS="-Wall -Werror"

# Before running the install phase we need to set up docker container that runs
# the target machine.
before_install:
  - docker run -d --name host -v $(pwd):/travis $HOST tail -f /dev/null
  - docker run -d --name dist -v $(pwd):/travis $HOST tail -f /dev/null
  - docker ps

# Update the container and install dependencies
install:
  - docker exec -t host bash -c "yes | apt-get update"
  - docker exec -t host bash -c "yes | apt-get upgrade"
  - docker exec -t host bash -c "yes | apt-get install build-essential device-tree-compiler libfdt-dev git clang-format-6.0"
  - docker exec -t dist bash -c "yes | apt-get update"
  - docker exec -t dist bash -c "yes | apt-get upgrade"
  - docker exec -t dist bash -c "yes | apt-get install build-essential device-tree-compiler libfdt-dev git clang-format-6.0"

# Here's where we actually run the test.
script:
# Check source code formatting
  - docker exec -t host bash -c "cd /travis && ./scripts/check-format"

# Build and check
  - docker exec -t host bash -c "cd /travis && ./configure"
  - docker exec -t host bash -c "cd /travis && make"
  - docker exec -t host bash -c "cd /travis && make install"
  - docker exec -t host bash -c "cd /travis && make check"
  - docker exec -t host bash -c "cd /travis && cat test-suite.log"

# Make distribution and check
  - docker exec -t host bash -c "cd /travis && make dist"
  - docker exec -t host bash -c "cd /travis && make distcheck"

# Untar distribution, build, and check
  - docker exec -t dist bash -c "cd /travis && tar -xvzpf freedom-devicetree-tools-*.tar.gz"
  - docker exec -t dist bash -c "cd /travis/freedom-devicetree-tools-*/ && ./configure"
  - docker exec -t dist bash -c "cd /travis/freedom-devicetree-tools-*/ && make"
  - docker exec -t dist bash -c "cd /travis/freedom-devicetree-tools-*/ && make install"
  - docker exec -t dist bash -c "cd /travis/freedom-devicetree-tools-*/ && make check"
  - docker exec -t dist bash -c "cd /travis/freedom-devicetree-tools-*/ && cat test-suite.log"
